exec {
  #systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK I3SOCK XCURSOR_SIZE XCURSOR_THEME
  dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK I3SOCK XCURSOR_SIZE XCURSOR_THEME
  /usr/lib/xdg-desktop-portal-gtk
  /usr/lib/xdg-desktop-portal-wlr
}

exec {
  "qs -c noctalia-shell"
  #mako
  lxqt-policykit-agent
  gammastep
  swayidle
  wl-paste --watch cliphist store
  # sway-audio-idle-inhibit
  wayland-pipewire-idle-inhibit

  "sleep 1 && gtk-launch google-chrome"
}

#exec_always ~/.config/waybar/sway/launch.sh
