
[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.primary]
background = "#000000"

[env]
TERM= "alacritty"
# TERM = "alacritty-direct"

[font]
# size = 14.0
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "FiraCode Nerd Font"
# family = "CommitMono Nerd Font"
# style = "Medium"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
# decorations = "none"
# opacity = 0.8

[general]
import = ["/home/ilya/.config/alacritty/tango_dark.toml"]
